# Generated by Django 5.0.1 on 2024-01-29 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Бренд')),
            ],
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255, verbose_name='Модель')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('horsepower', models.IntegerField(default=0, verbose_name='Лошадиные силы')),
                ('mileage', models.IntegerField(default=0, verbose_name='Расход')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars_api.carbrand', verbose_name='Бренд')),
            ],
        ),
    ]
