# Generated by Django 5.0.1 on 2024-01-31 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cars',
            new_name='Car',
        ),
    ]
