# Generated by Django 5.0.1 on 2024-01-31 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars_api', '0003_remove_car_horsepower'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='brand',
        ),
    ]
