# Generated by Django 5.0.1 on 2024-01-31 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_api', '0004_remove_car_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars_api.carbrand', verbose_name='Бренд'),
            preserve_default=False,
        ),
    ]
