# Generated by Django 5.0.1 on 2024-01-31 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_api', '0009_carbrand_car_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Cars', to='cars_api.carbrand', verbose_name='Бренд'),
        ),
    ]
