# Generated by Django 5.0.1 on 2024-02-03 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_api', '0010_alter_car_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbrand',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
