# Generated by Django 5.0.1 on 2024-02-03 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_api', '0011_alter_carbrand_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.CharField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.IntegerField(default=0, verbose_name='Пробег'),
        ),
    ]
